### ISSUE TITLE
P1e - Design the wireframes for the web site

### ISSUE THREAD

**Issue by louis-0** [PaulShunOSAWA/web-develop-t1g1-aqt#8]
Produce a set of wireframes for the site, showing the concepts for both a wide screen and small screen. These can either be drawn by hand or produced using a tool such as PowerPoint or a graphics package such as Illustrator. Avoid painting or photo-editing software such as Paint or Photoshop as designs produced in this way are difficult to edit. Ensure that the designs are clear and easy to read.

**Criteria:**
- Design of the wireframes as a clear model for the web site

Criteria 5: Design of the wireframes as a clear model for the web site
• No design of the wireframes as a clear model for the web site presented (0 pts)
• Untidy or sparse design of the wireframes as a clear model for the web site
presented (0.5 pts)
• Comprehensive design of the wireframes as a clear model for the web site
presented (1 pt)

Bundled team assignment submission:
5. Design of the wireframes as a clear model for the web site
• No wireframes provided or wireframes not in suitable format. (0 pts)
• Wireframes are either too vague or are clearly drawn from the finished pages (too
specific). (1 pts)
• Wireframes show appropriate level of planning and detail. Where designs have
been changed, this is made clear. (2 pts)

**Comment by louis-0** [comment]
[2.4.3 Team Assignment - Wireframes.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7698844/2.4.3.Team.Assignment.-.Wireframes.pdf)

**Comment by louis-0** [comment]
Shun OSAWA an hour ago
@apirich Thank you Api for applying our discussion to the wireframe! However, to be honest, I would like to use Louis's design. Firstly, Louis's design was so great because the layout is reflected the times and some margin between several contents is also suitable I analyzed 5 websites and the layout I saw was similar to Louis's one. Further, I work as a photographer in Japan. So I might understand what design is beautiful. So I'd love to suggest that we use Louis's design and then apply. Api's contents.

Api Rich Dec 10 at 1:27 AM (edited)
@jez150 @shunosawa @louishuynh11 I made a wireframe base on the content and structure that we discussed, please have a look on it, discuss and upload necessary photos/slide/videos so we can make final agreement and go to the next step. Btw, what should we name our park, or just simply Park/ Theme Park?

Reply
Api Rich attached sub-page 2.pdf to this card Dec 10 at 1:23 AM 
Reply
Api Rich attached sub-page 1.pdf to this card Dec 10 at 1:23 AM 
Reply
Api Rich Dec 10 at 1:22 AM (edited)
mainpage.pdf

sub-page 1.pdf

sub-page 2.pdf

Reply
Api Rich attached mainpage.pdf to this card Dec 10 at 1:22 AM 
Reply
Shun OSAWA Nov 29 at 9:52 AM (edited)
Here is our theme park directory I created
https://drive.google.com/drive/folders/1dmVOkQUrGW9WJTc0bcXNwJl2-lvO3ZC2?usp=sharing

I do not want to link my google drive to Trello so that I post the URL to download the directory. I'm sorry!

Reply - Add link as attachment - Delete
Shun OSAWA Nov 29 at 9:40 AM
I created top page referencing this wireframe.
wireframe

Reply - Delete
Shun OSAWA attached Screen Shot 2021-11-29 at 11.37.34 PM.png to this card Nov 29 at 9:39 AM
Reply
Shun OSAWA Nov 29 at 8:03 AM
Really good! smile Thanks a lot!!

Reply - Delete
Louis Huynh attached Wireframes for 3 pages to this card Nov 28 at 3:02 PM 
Reply
Louis Huynh moved this card from TODO 📚 to DOING ⚙️
Nov 28 at 3:01 PM
Jez deleted the IMG_4050.jpg attachment from this card
Nov 26 at 6:40 PM
Jez deleted the IMG_4049.jpg attachment from this card
Nov 26 at 6:40 PM
Jez attached IMG_4050.jpg to this card Nov 26 at 6:39 PM 
Reply
Jez attached IMG_4049.jpg to this card Nov 26 at 6:39 PM 
Reply
Louis Huynh added this card to TOD

**Comment by louis-0** [comment]
[sub-page_2.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7698849/sub-page_2.pdf)
[mainpage.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7698850/mainpage.pdf)
[sub-page_1.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7698851/sub-page_1.pdf)

**Comment by louis-0** [comment]
[2.4.3 Team Assignment - Wireframes.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7698844/2.4.3.Team.Assignment.-.Wireframes.pdf)

For page 2, should we remove the hotel reservation? If not necessary, then we can simplify?

**Comment by Apirich** [comment]
This was supposed to be discussed as part 1 on Trello, not on this part and not here!

**Comment by Apirich** [comment]
And I don't think we should remove hotel reservation at all, because if we remove, there will be only a page that contents 3/2 types of ticket, no need to be simplified. The things we should simplify is the navigation bar. 5 tabs for the navigation of the 3 pages website is confusing.

**Comment by louis-0** [comment]
You make a good point. 

I recall from your research, Adventurecity.com keeps things relatively simple. Although their checkout page implements several pages and javascript, the content structure itself for users to checkout is quite basic. 

Perhaps, we can take a couple ideas from them, and instead of having a multi page checkout, should the visitor/user clicks the buy tickets button, a popup can request user to enter payment and client info (eg. email, etc.). Essentially, this would complete the checkout process in one dedicated page. 

If there's another simpler process, then that would be preferred to reduce any complexities and workload.

https://adventurecity.showare.com/eventperformances.asp?evt=1

**Comment by Apirich** [comment]
@louis-0  Yes, I did mention to make thing simple in a sense that providing example for each category because if so we will end up using the same semantic tags (for instance: if we already have 2 in attractions and rides, we don't need another 3 or 4, or if navigation already has 3- 4 tabs, then don't need another 5th or 6th tab, or as your original wireframe, if already 2-3 FAQs then it is unnecessary to add 8-10.) As well as tickets and passes, 3 tickets and/or passes is well enough if that page is going together with hotel reservations or online items, NOT A WHOLE PAGE WITH ONLY 3 TICKETS. 

I said keeping things simple, not removing things to make it lacking of information. And for your info as well, at the time we discussed about keeping things simple, even until now, removing hotel reservation is not my idea (even though Khalid and I are taking care of ticket page), it is your idea.

Attached your original list below in case you're confusing about being simple and lacking of information.

List of Content (aggregated from previous research)

About Us
o Contact us
o Our values
o IP partnerships
o Our history
Plan Your Visit
o Park Highlights
o Pre-Arrival Tips
o Health and Safety Protocols
 Covid health & safety protocols
o Property Rules
o Guests with Disabilities
o Lost and found
o FAQ
Reservations:
o Park passes & ticket purchases
 Details of items for sale
 Discounts
 One day entry & season passes
 Rides & line bypasses,
o Calendar & hours of operations
o Park map
o Directions & parking
o Places to Stay
 Hotels & spas
 Offers and discounts
 Check reservations
 Vacation packages
Things to Do
o Rides and Attractions
 Thrill Rides
 Family Rides
 Kid Rides
o Restaurants and dining
 Reservations
o Entertainment
 Live shows
 3d movies
 Events; holidays & seasonal activities
o Recreation
 Indoor pools @ Hotel & Spa
 Outdoor poolside Cabanas
 Fitness Centers and Activities
o Shop & Gifts

**Comment by louis-0** [comment]
> same semantic tags (for instance: if we already have 2 in attractions and rides, we don't need another 3 or 4, or if navigation already has 3- 4 tabs, then don't need another 5th or 6th tab, or as your original contents, if already 2-3 FAQs then it is unnecessary to add 8-10.) As well as tickets and passes, 3 tickets and/or passes is well enough if that page is going together with hotel reservations or online items, NOT A WHOLE PAGE WITH ONLY 3 TICKETS.

I'm not sure what you mean. We all understand that semantic tags and the actual information covered using FAQs for the hypothetical clients are different, right? So, can you please elaborate your interpretation of semantic tags again? It would be great help to all.

> I said keeping things simple, not removing things to make it lacking of information. And fyi as well, at the time we discussed about keeping things simple, even until now, removing hotel reservation is not my idea.

Okay, since you're managing page 2 with Khalid and you're quite adamant on keeping this hotel section, then it seems as though it would be best that you both make the last decision. Since the hotel reservation feature has minimal relation to the index page or page 1. 

> Btw, attached your original list below in case you're confusing about being simple and lacking of information. Because I saw in your original list, there are 4 sub-parts of reservation, and we agreed to go with 2 (ticket/pass and hotel), and right now, even agreed to go with only 1, so just my little concern, is it making things simple or is it ridiculously making things simple?

Reservations:
o Park passes & ticket purchases
 Details of items for sale
 Discounts
 One day entry & season passes
 Rides & line bypasses,

Is this list you're mentioning? As I've mentioned, this was research for us to simply discuss. If you like it, then feel free to implement. If you don't like, then feel free to not to use it and change/adjust as you please. I think we're all malleable here. 

> And thanks for your concern about workload, Khalid and I are actually good to code some more lines for the ticket page. And I will update the html ticket page by myself as well, so if there is any academic issues or complexities for you to contribute on the ticket page, please address it. We are willing to support as a team.

Thanks for the support. For future reference, this is an open-ended discussion and collaborative effort. So, feel free to raise and address any concerns; as I will mine.

> And I agree with you on Javascript, but I don't think UOL will grade us about Javascript part, which means as long as we have correct html tags and CSS, we will get full mark (still need to be confirmed thus if this issue worried you). And yes, we just need button/cart icon/form, we don't need php or Javascript or anything to store the data. It will be just raw HTML as required. ALSO, IT IS TOTALLY DIFFERENT BETWEEN HOTEL RESERVATIONS AND CHECK OUT PAGE, so do you mean Hotel Reservation or check out page?

> As well as tickets and passes, 3 tickets and/or passes is well enough if that page is going together with hotel reservations or online items, NOT A WHOLE PAGE WITH ONLY 3 TICKETS.

> Already asked Khalid not to add hotel reservations days ago. No further discussion need on ticket page for me.

Okay, so we're on a mutual understanding that we're not using JS or php.  I was simply stating that hotel reservation is unnecessary. But, I'm unsure of what you're asking me now. These statements are contradicting and confusing. 

Since the tickets page is both you and Khalid's responsibility, you both can also make the last decisions. So, if you have any other changes or input, please redevelop and submit a new wireframe for the tickets page with semantics marked up. It'll help clarify your perspective and for us to understand what you trying to mean. You can simply refer to all previous work regarding tickets page as a rough draft.

**Comment by Apirich** [comment]
No, you were not simply stating that hotel reservations is uneccessary. You mentioned about my Adventure City research that I said it is simple while their checkout page is not, which is not true and unnecessary at all while I already have agreed removing hotel reservation, and so I thought you are confusing about what I meant to be simple, so I explained. Well, I said what I want to say, either you get it or not, it is ok. Like I said, no further discussion need on my side. Ticket page is done now, I'm checking on it and will submit updated html wireframe for it.

**Comment by louis-0** [comment]
@Apirich @PaulShunOSAWA @alkhalid49  

> Yes, I did mention to make thing simple in a sense that providing example for each category because if so we will end up using the same semantic tags (for instance: if we already have 2 in attractions and rides, we don't need another 3 or 4, or if navigation already has 3- 4 tabs, then don't need another 5th or 6th tab, or as your original contents, if already 2-3 FAQs then it is unnecessary to add 8-10.) As well as tickets and passes, 3 tickets and/or passes is well enough if that page is going together with hotel reservations or online items, NOT A WHOLE PAGE WITH ONLY 3 TICKETS.
> 
> I said keeping things simple, not removing things to make it lacking of information. And fyi as well, at the time we discussed about keeping things simple, even until now, removing hotel reservation is not my idea.
> 
> This is my research on Adventure City, where did I mention they keeps things relatively simple????
> 
> Adventure City [Adventure City Family Amusement Park, Fun Attractions & Games](https://www.adventurecity.com/) Pros: "Lost and found" is useful. Has "jobs offers". Cons: "Attraction list" should have photos to be recognized. Colors are nice, but a little bit too strong.

Please excuse me if I don't understand what you're trying to discuss here. Either way, if there's nothing to discuss, then there was no need to address this to me initially.

You can disregard anything related to checkout page. Great work with tickets page!
