### ISSUE TITLE
P2a - Markup wireframes with HTML

### ISSUE THREAD

**Issue by louis-0** [PaulShunOSAWA/web-develop-t1g1-aqt#9]
Review the three wireframes that you produced for the large screen version of your web site from part 1 of the team project and make any changes that you think would improve them. Work through the wireframes and decide on the correct HTML to build those pages. Think carefully about the use of layout tags such as tables, and only use them where content is really a table. Make sure that all the parts of the pages have a semantic identity, either by using existing semantic tags or by defining "div" tags for the content. Attempt to use a range of the various formatting tags available to add richness and extra meaning to your content. Consider how different media can add to the way that your pages communicate information.

Mark up your wireframes with the HTML tags that you intend to use. Upload these marked-up wireframes in a .zip file into the Workspace: static web pages that is located in the end of week 10  and generate a shareable URL. Consider how your HTML supports the use of your pages by users with disabilities.

Peer submission:
Criteria 1: Appropriate semantic tags used, both the predefined tags and the appropriate
use of div block tags.
• No evidence of appropriate semantic tags used, both the predefined tags and the
appropriate use of div block tags. (0 pts)
• Sparse use of appropriate semantic tags used, both the predefined tags and the
appropriate use of div block tags. (0.5 pts)
• Comprehensive use of appropriate semantic tags used where all significant
semantic spaces in the pages are defined semantically, both the predefined tags
and the appropriate use of div block tags. (1 pt)

Bundled team submission:
6. Appropriate use of semantic tags
• No semantic tags used, or tags appear, but are misused. (0 pts)
• Semantic tags are used, tags are always appropriate. (1 pts)
• Comprehensive use of semantic tags. All (or almost all) significant semantic spaces
in the pages are defined semantically. All (or almost all) content is contained in a
block whose purpose is identifiable. (2 pts)

**Comment by PaulShunOSAWA** [comment]
> make any changes that you think would improve them

According to this,  we can carry out making three pages without making over Louis's great wireframe adding some changes we discussed.

**Comment by louis-0** [comment]
I believe this question is determining our understanding of html semantics. It was mentioned that semantics structures are preferred over div blocks. 

I usually code in Python. So, this is my first time wrapping my mind around HTML semantics. However, I'm still not sure, so please let me know if there are any improvements. 

@PaulShunOSAWA I understand you've put in a lot of work already. And what I'm proposing may conflict with your current code. So, I apologize ahead of time. However, please let me know your thoughts first. 

##Header
 
<header>
<object> Logo
<nav>
<ul> 
<li><a href=”#”> Things to Do
<li><a href=”#”> Contact Us
<li><a href=”#”> Buy Tickets

##Main Page

<main>

<article class="main page">
<h1>Headline
<p>Description
<button>Buy Now


<section class=”carousel media”>

<article class=”media 1”>
<figure> Add media 1

<article class=”testimonials”>
<h2>Testimonials
<section class=”main_review”>
<h3>Review
<p>Great! 5 star review

<section class=”user_reviews”>
<h3>User reviews

<article class=”user_review”>
<h4>Review title 1
<p>Review 1
<footer>
<p> Posted on <time>
<article class=”user_review”>
<h4>Review title 2
<p> Review 2
<footer>
<p> Posted on <time>

<article class="Preview Things to do">
<h2>Preview 'Things to do'
<p>Description

<section class=”Preview Things to do”>
<h3> Rides & Attractions
<p> description
<a href=”mysubpage2.html#rides&attractions”>Rides & Attractions

<article class="FAQ">
<h2> FAQ
<p> Description

<dl> FAQs
<dt> Q1
<dd> A1

##Page 1
!-- Sub-page 1 -->
<main>

<article class="Things to do">
<h1> Headline
<p> Description


<section class=”carousel media”>

<article class=”media 1”>
<figure> Add media 1

<article class="rides & attractions">
<h2>Rides & Attractions
<p>description

<section class="The Ferris Wheel">
<h3>The Ferris Wheel
<p> 
<figure> Ferris wheel

<article class=”events and shows”> 
<h2>Events & Shows
<p>description

<section class="Joy of holiday season">
<h3> Joy of holiday season:
<p> 
<figure> Joy of holiday image

<article class="Dining">
<h2>Dining
<p>description

<section class="three broomsticks restuarant">
<h3>Three Broomsticks restaurant
<p> 
<figure>restuarant picture

##Page 2

<main>

<article class="reservations and tickets">
<h1> Headline
<p> Description


<section class=”carousel media”>

<article class=”media 1”>
<figure> Add media 1

<article class="find hotel room">
<h2>Make a reservation
<p>
<button>Choose Date
<input># of rooms
<input># of guests
<button>Check availability

<article class="passes and tickets">
<h2> Get Your Tickets Today!
<p>

<section class=”Package1”>
<figure> Image Package 1
<h3> Package 1
<ul> Benefit list for package 1
<button>Buy now <form><input>

##Footer: Park Info 
<footer>
<table> Opening hours description; okay to present data, not layout
<address> Address & Park map descriptions and embedded map
<a href=”mailto:”>Contact us: descriptions/contact form

Endnote:
	Based on previously researched theme parks, aside elements aren’t applied anymore. This may be due to design conflicts for mobile responsive layouts

**Comment by PaulShunOSAWA** [comment]
Thank you so much Louis. I'm going to update them referring to your great work. I already have created this attached file and added it to our main folder. However, your work is apparently better.
[wireframe with HTML.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7773041/wireframe.with.HTML.pdf)

**Comment by PaulShunOSAWA** [comment]
It may be impossible to put all of your great work on wireframe. 
So, 

A: Could I cut a part of them and overlap it on wireframe ?
Or 
B: do we leave both of them? Such that the pictured one and the described one. Like this.

[wireframe with HTML.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7773204/wireframe.with.HTML.pdf)

**Comment by louis-0** [comment]
Ref links:
- https://clearlydecoded.com/modern-html-semantic-elements

So, based on modern semantics, it seems as though we'd want to code our page using SEO friendly methods. From my research, it seems we need to learn how to wrap sections within articles blocks instead of using generic div blocks.

Some parts seems a bit tricky to do this, such as for the Carousel Media. But once we comprehend this, I think it's quite simple. This should also make our CSS stylesheet a bit clearer, than referencing to many div block ids.

As for JS, I don't think that's part of our project. I believe the project want us to code this our using 100% html and css. 

In regards to the checkout page, with Hotel Reservations, I think we should cut this out because it doesn't seem necessary for a theme park and ultimately, would reduce the complexity of the codebase - simple is better. So, my proposition it to remove the Make a Reservation section and keep the rest; we'll just replace the main picture with another relatable picture for ticket sales.

Again, I think this section is one of the most important parts to our project to reduce any further backtracking. Let me know your thoughts.

**Comment by PaulShunOSAWA** [comment]
Thank you for researching, and I got it. It's important to be simple in many ways. Hence I agree with you.
About the JS,  I understand. I will remove some JS features, and let's look for an instead method. 

In regards to the checkout page, with Hotel Reservations, I think we should cut this out because it doesn't seem necessary and would require additional logic to make this feature work reasonably correctly. So if we remove this part, ultimately, this would reduce the complexity of the codebase - simple is usually better. So, my proposition it to remove the 'Make a Reservation' section and keep the rest; we'll just replace the main picture with another relatable picture for ticket sales.
→I agree with you.

**Comment by Apirich** [comment]
[wfHtml main.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7777418/wfHtml.main.pdf)
[wfHtml subpage1.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7777419/wfHtml.subpage1.pdf)
[wfHtml subpage2.pdf](https://github.com/PaulShunOSAWA/web-develop-t1g1-aqt/files/7777420/wfHtml.subpage2.pdf)

Since my idea is a little bit different but @PaulShunOSAWA and @louis-0 's ideas also work for me so I agree with what you both just discussed above. 

However, there is a part for "Submission of the individual reflective piece" so I attached my HTML wireframe here for contribution purpose only.

The HTML wireframe for page 2, still has hotel reservation, so if we all agree to remove it, please adjust it as well. And if no further discussion need to be made on this part, we should discuss about "What to do". 

Btw, is Khalid still with us?

**Comment by Apirich** [comment]
Never mind, I and Khalid will do the ticket page, and I will update html wireframe for ticket page base on Louis' wireframe.
